### ISSUE TITLE
State Change Events question

### ISSUE THREAD

**Issue by LBreedlove** [alexandrnikitin/CircuitBreaker.Net#10]
Is there a specific reason the `ICircuitBreakerEvents` interface isn't used or implemented anywhere?
I was thinking about adding support for the state change events to `CircuitBreaker`, but wanted to see why they weren't there first.
Thank you.

**Comment by alexandrnikitin** [comment]
Lucas, thanks for raising this. Yes, I intended to add events and an extensibility point via events. I just didn't find a need yet. I will be glad to see a PR if you have time for this. 😉

**Comment by LBreedlove** [comment]
Is there any concern about two consecutive state changes occurring in quick succession, and potentially triggering the events out of order?

**Comment by alexandrnikitin** [comment]
I don't have a strong opinion on that. But I would avoid any locking and keep the code as thin as possible. Maybe atomic event version via `Interlocked.Increment` could solve that? Do you have a particular use case in your mind?

**Comment by alexandrnikitin** [comment]
I would also avoid any allocation if it's possible at all. I want to keep the library as unobtrusive and thin as possible. Maybe just interface with methods (not events) would be a better option, with a default null implementation and ability to specify a custom one. I don't have a strong opinion on this either. 😕

**Comment by LBreedlove** [comment]
Use case: I have a pool of related, remote resources. They can fail or slow down independently, but the remote system can also fail as a whole. If an individual resource is slow or failing, I'm fine with directing requests for that resource to another queue for processing later. However, if many of the remote resources are failing, I want the system to slow down, stop dropping requests, and wait for the remote system to stabilize. I think I need the events to be able to monitor all the instantiated CircuitBreaker's and switch into a "wait for recovery" mode if too many are "Opened". I could also just check the state of the CircuitBreaker's periodically, but I don't think that would be as reliable, as multiple state changes could occur between polls. Perhaps there's a better way I haven't considered?

**Comment by alexandrnikitin** [comment]
The easiest way is to inject some logic into `try catch` block 😄 But using events or an interface is indeed a more reliable way to do it. Another option is to expose `ICircuitBreakerSwitch` via construction or a builder class. (and other interfaces too ie `ICircuitBreakerInvoker`, `ICircuitBreakerState`)

**Comment by alexandrnikitin** [comment]
@LBreedlove I've just published [v0.6.0](https://www.nuget.org/packages/CircuitBreaker.Net/0.6.0)
