### ISSUE TITLE
.Net Core 2 Support

### ISSUE THREAD

**Issue by Caldas** [alexandrnikitin/CircuitBreaker.Net#13]
It would be nice to support .net core 2 projects

![image](https://user-images.githubusercontent.com/938045/32007284-e488de02-b987-11e7-9615-d7e7b968b939.png)

**Comment by alexandrnikitin** [comment]
@Caldas Thank you for raising the issue. I agree that library needs .NET Core support, probably .NET Standard 1.3 (or even 1.1) will be a good target. Will you be able to find time for that?

**Comment by NiklasArbin** [comment]
To support .net core you would need to change the build pipeline as well. I can look into upgrading to Net Standard, but not the build and packaging. Would that be helpful to you?

**Comment by alexandrnikitin** [comment]
Closed via #14. `0.7.0` version targets .NET Standard.
