### ISSUE TITLE
Cannot use from signed assembly

### ISSUE THREAD

**Issue by grzesiek-galezowski** [alexandrnikitin/CircuitBreaker.Net#4]
The assemblies complain that CircuitBreaker.NET does not have a strong name.

**Comment by grzesiek-galezowski** [comment]
Hi,

I could help with that, I just need a decision on which way to choose. Some libraries like nunit just [embed the key to sign the assembly inside their repository](https://github.com/nunit/nunit/blob/master/src/nunit.snk). This would be the easiest choice if acceptable and would allow the assembly to be referenced from ones that have strong names already.

**Comment by alexandrnikitin** [comment]
@grzesiek-galezowski That would be great! I'm OK with embedding the key into the repository 😉

**Comment by alexandrnikitin** [comment]
@grzesiek-galezowski Just one request: it would be awesome to have it automated via FAKE build script.

**Comment by grzesiek-galezowski** [comment]
I'll try to get at it today. Normally the way I sign the assembly, I just enable this feature from Visual Studio so that it happens automatically during project build. It is reflected in csproj by lines such as (example taken from NUnit):

``` xml
<SignAssembly>true</SignAssembly>
<AssemblyOriginatorKeyFile>..\..\nunit.snk</AssemblyOriginatorKeyFile>
```

This is the easiest way. Would this be OK with you?

**Comment by alexandrnikitin** [comment]
That part is ok. But what about the nuget package? Do you want it to be one package or a separate package for the signed version?

**Comment by grzesiek-galezowski** [comment]
Other projects I looked at don't have a separate signed nuget - the default ships a signed assembly. I don't know of any case where a signed assembly doesn't work but unsigned does. The only thing I know of that is lost is that a signed assembly cannot reference unsigned assemblies (so CI.NET could not reference unsigned nugets). 

What I see on nuget is that some libraries just ship as signed (I think e.g. Reactive Extensions but I'd need to confirm it) and [some have a signed counterpart](https://www.nuget.org/packages?q=signed). My initial preference was to leave a single nuget containing a signed assembly, however, I can change that approach if you wish.

**Comment by alexandrnikitin** [comment]
I don't have strong opinion on this. I saw both approaches and either is fine for me. I think one signed assembly would be enough.
