### ISSUE TITLE
Inheritence of Exceptions

### ISSUE THREAD

**Issue by NiklasArbin** [alexandrnikitin/CircuitBreaker.Net#8]
Hi, really great library!

Would be nice at clientside be able to simplify some code if all CircuitBreaker Exceptions would derive from the same base Exception so not all code has to catch all specific types.

**Comment by alexandrnikitin** [comment]
Hi Niklas! Great idea! I'll add a base class for them.

**Comment by alexandrnikitin** [comment]
Published v0.5.0

**Comment by NiklasArbin** [comment]
Great, thanks!
